server:
  port: 8080

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - metrics-requiredMetricName
          - prometheus
          - loggers
          - health
  endpoint:
    health:
      probes.enabled: true
      show-details: always
      livenessState.enabled: true
      readinessState.enabled: true
    metrics.enabled: true
    prometheus.enabled: true
    metrics:
      export.prometheus.enabled: true
      distribution:
        percentiles-histogram.http.server:
          requests: true
        sla.http.server.requests: 50ms, 100ms, 200ms, 400ms
        percentiles.http.server:
          requests: 0.5, 0.9, 0.95, 0.99, 0.999

db:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  schema: ${DB_SCHEMA:spring-starter}
  username: ${DB_USERNAME:postgres}
  password: ${DB_PASSWORD:secret}
  endpoint: "${db.host}:${db.port}/${db.schema}"

spring:
  application:
    name: spring-starter
  r2dbc:
    url: "r2dbc:postgresql://${db.endpoint}"
    username: ${db.username}
    password: ${db.password}
  flyway:
    enabled: true
    url: "jdbc:postgresql://${db.endpoint}"
    user: ${db.username}
    password: ${db.password}

springdoc:
  swagger-ui:
    path: /api-docs
    operations-sorter: method
